workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

include:
  - project: 'devops_community/the-way-of-cicd-open-source-edition'
    ref: $CI_COMMIT_REF_NAME
    file:
      - 'version/version.yml'
      - 'release/release.yml'

stages:
  - version
  - release

version:
  stage: version
  extends:
    - .version_git

create-release:
  stage: release
  extends:
    - .release